server:
  port: 8081

spring:
  application:
    name: category-service
  profiles:
    active: dev
  messages:
    basename: i18n/messages

## Swagger Configuration
category:
  swagger:
    title: Category Service
    description: Category Service Rest API
    license: MIT License
    licenseUrl: https://opensource.org/licenses/MIT
    version: 1.0